

web:
  image: rakudo-star:2015.03 # https://registry.hub.docker.com/_/rakudo-star/
  command: perl6 /app/web/app.pl
  volumes:
    - web/src:/app/web
  links:
    - db
  env_file:
    - .env_db
  ports:
    - "3000:3000"

db:
  image: postgres:9.1
  volumes:
    - db/data:/var/lib/postgresql/data
    - db:/app/db
  env_file:
    - .env_db

